# Generated by Django 3.0.8 on 2020-08-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Город')),
                ('cityAlias', models.CharField(max_length=30, null=True, verbose_name='Склонение города (должно отвечать на вопрос ГДЕ, например, Москве)')),
                ('region', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Регион')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Коэффициент стоимости размещения')),
                ('sub_domain', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Название поддомена(на пример msk)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Домен по умолчанию?')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города и регионы',
            },
        ),
    ]
