# Generated by Django 4.0.6 on 2022-10-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('-order_num', '-city'), 'verbose_name': 'Город', 'verbose_name_plural': 'Города и регионы'},
        ),
        migrations.AddField(
            model_name='city',
            name='order_num',
            field=models.IntegerField(default=1000, verbose_name='Номер ПП'),
        ),
    ]
