# Generated by Django 3.0.8 on 2020-09-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
