# Generated by Django 3.0.8 on 2020-09-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_delayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_user_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='show_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
