# Generated by Django 3.0.8 on 2020-09-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20200906_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='chat_id',
            field=models.IntegerField(default=0),
        ),
    ]
