# Generated by Django 3.0.8 on 2020-07-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0002_auto_20200730_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techniqueunit',
            old_name='rent_type_hour',
            new_name='rent_type',
        ),
        migrations.RemoveField(
            model_name='techniqueunit',
            name='rent_type_day',
        ),
        migrations.AlterField(
            model_name='techniquecategory',
            name='image',
            field=models.ImageField(null=True, upload_to='technique/type/', verbose_name='Изображение (265 x 185)'),
        ),
    ]
