# Generated by Django 3.0.8 on 2020-07-30 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0003_auto_20200730_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniquecategory',
            name='is_show_at_index',
            field=models.BooleanField(default=False, verbose_name='Отображается на главной?'),
        ),
        migrations.AlterField(
            model_name='techniquetype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='technique.TechniqueCategory', verbose_name='Категория'),
        ),
    ]
