# Generated by Django 3.0.8 on 2020-07-30 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0004_auto_20200730_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniquefilter',
            name='from_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='from_value'),
        ),
        migrations.AddField(
            model_name='techniquefilter',
            name='to_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='to_value'),
        ),
        migrations.AlterField(
            model_name='techniquefiltervalue',
            name='filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='values', to='technique.TechniqueFilter', verbose_name='Фильтр'),
        ),
    ]
