# Generated by Django 3.0.8 on 2020-07-30 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0006_auto_20200730_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechniqueUnitImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='technique/items/', verbose_name='Изображение')),
                ('is_moderated', models.BooleanField(default=True, verbose_name='Изображение проверено?')),
                ('techniqueitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='technique.TechniqueUnit', verbose_name='Изображение для')),
            ],
        ),
    ]
