# Generated by Django 3.0.8 on 2020-07-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0007_techniqueunitimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniqueunitimage',
            name='image_thumb',
            field=models.ImageField(null=True, upload_to='technique/items/', verbose_name='Изображение уменьшенное'),
        ),
    ]
