# Generated by Django 3.0.8 on 2020-07-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0008_techniqueunitimage_image_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniquefilter',
            name='value',
            field=models.CharField(default='', max_length=255, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='techniqueunitimage',
            name='image_thumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='technique/items/', verbose_name='Изображение уменьшенное'),
        ),
    ]
