# Generated by Django 3.0.8 on 2020-08-06 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technique', '0009_auto_20200730_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniqueunit',
            name='rate_value',
            field=models.IntegerField(default=0, verbose_name='Сумма оценок'),
        ),
        migrations.AlterField(
            model_name='techniquefilter',
            name='from_placeholder',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='From placeholder'),
        ),
        migrations.AlterField(
            model_name='techniquefilter',
            name='from_value',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='from_value'),
        ),
        migrations.AlterField(
            model_name='techniquefilter',
            name='placeholder',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Placeholder'),
        ),
        migrations.AlterField(
            model_name='techniquefilter',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок блока фильра'),
        ),
        migrations.AlterField(
            model_name='techniquefilter',
            name='to_placeholder',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='To placeholder'),
        ),
        migrations.AlterField(
            model_name='techniquefilter',
            name='to_value',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='to_value'),
        ),
        migrations.AlterField(
            model_name='techniquefilter',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='techniqueunit',
            name='filter_value',
            field=models.ManyToManyField(blank=True, related_name='unit_filter_values', to='technique.TechniqueFilterValue', verbose_name='ФильтрыЗначения'),
        ),
        migrations.AlterField(
            model_name='techniqueunit',
            name='rate_times',
            field=models.IntegerField(default=0, verbose_name='Кол-во отзывов'),
        ),
        migrations.CreateModel(
            name='TechniqueUnitFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Тест')),
                ('value', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отзыв от')),
                ('techniqueitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_feedbacks', to='technique.TechniqueUnit', verbose_name='Отзыв для')),
            ],
        ),
    ]
