# Generated by Django 3.0.8 on 2020-08-10 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technique', '0011_techniquefiltervalue_is_show_in_item_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniqueunit',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
