# Generated by Django 3.0.8 on 2020-08-23 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0013_auto_20200823_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechniqueUnitImageDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='technique/items/', verbose_name='Документы')),
                ('techniqueitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='technique.TechniqueUnit', verbose_name='Документы для')),
            ],
        ),
    ]
