# Generated by Django 3.0.8 on 2020-08-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0014_techniqueunitimagedoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniqueunit',
            name='coords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Координаты'),
        ),
    ]
