# Generated by Django 3.0.8 on 2020-09-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0017_techniquetype_orders_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniquetype',
            name='orders_count',
        ),
    ]
