# Generated by Django 3.0.8 on 2020-09-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0018_remove_techniquetype_orders_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniqueunit',
            name='in_rent',
            field=models.BooleanField(default=False, verbose_name='В аренде?'),
        ),
    ]
