# Generated by Django 3.0.8 on 2020-09-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0019_techniqueunit_in_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniquecategory',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Стоимость размещения'),
        ),
    ]
