# Generated by Django 3.0.8 on 2020-10-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0020_techniquecategory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniqueunit',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
