# Generated by Django 3.0.8 on 2020-10-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0021_techniqueunit_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniquefiltervalue',
            name='label_lower',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='label'),
        ),
    ]
