# Generated by Django 3.1.5 on 2021-02-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0022_techniquefiltervalue_label_lower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techniquecategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='techniquefilter',
            options={'verbose_name': 'Фильтр', 'verbose_name_plural': 'Фильтры'},
        ),
        migrations.AlterModelOptions(
            name='techniquefiltervalue',
            options={'verbose_name': 'Значение фильтра', 'verbose_name_plural': 'Значения фильтров'},
        ),
        migrations.AlterModelOptions(
            name='techniquetype',
            options={'verbose_name': 'Тип техники', 'verbose_name_plural': 'Типы техники'},
        ),
        migrations.AlterModelOptions(
            name='techniqueunit',
            options={'verbose_name': 'Еденица техники', 'verbose_name_plural': 'Еденицы техники'},
        ),
        migrations.AddField(
            model_name='techniqueunit',
            name='ad_price',
            field=models.IntegerField(default=0, verbose_name='Стоимость объявления'),
        ),
    ]
