# Generated by Django 3.1.5 on 2021-03-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0023_auto_20210222_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techniqueunit',
            options={'ordering': ('-is_vip', '-promote_at'), 'verbose_name': 'Еденица техники', 'verbose_name_plural': 'Еденицы техники'},
        ),
    ]
