# Generated by Django 3.1.5 on 2021-03-24 07:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0024_auto_20210320_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniquefilter',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
