# Generated by Django 3.1.5 on 2021-03-24 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0025_techniquefilter_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniquefilter',
            name='uuid',
        ),
        migrations.AddField(
            model_name='techniqueunit',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
