# Generated by Django 4.0.6 on 2022-10-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0027_alter_techniqueunitfeedback_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniqueunit',
            name='promote_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата поднятия'),
        ),
    ]
