# Generated by Django 4.0.6 on 2022-11-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0029_alter_techniqueunit_rent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniqueunitimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
