# Generated by Django 3.0.8 on 2020-08-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200810_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rentDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='rentEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='rentEndTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='rentStartDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='rentStartTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='rentType',
            field=models.BooleanField(default=True),
        ),
    ]
