# Generated by Django 3.0.8 on 2020-09-23 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_auto_20200922_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='chatusers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
