# Generated by Django 4.0.6 on 2022-11-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_rentkm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='rentType',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
