# Generated by Django 3.0.8 on 2020-08-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rate_times',
            field=models.IntegerField(default=0, verbose_name='Кол-во отзывов'),
        ),
        migrations.AddField(
            model_name='user',
            name='rate_value',
            field=models.IntegerField(default=0, verbose_name='Сумма оценок'),
        ),
    ]
