# Generated by Django 3.0.8 on 2020-08-23 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        ('user', '0003_auto_20200810_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tariff_expire',
            new_name='vip_expire',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tariff_update',
            new_name='vip_update',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.City', verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_person',
            field=models.BooleanField(default=True, verbose_name='Частное лицо?'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Акканнт подтвержден?'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='VIP?'),
        ),
        migrations.AddField(
            model_name='user',
            name='ogrn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='Иван', max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='Иванов', max_length=50, null=True, verbose_name='Фамилия'),
        ),
    ]
