# Generated by Django 3.0.8 on 2020-08-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200823_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название организации'),
        ),
    ]
