# Generated by Django 3.0.8 on 2020-09-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0018_remove_techniquetype_orders_count'),
        ('user', '0005_user_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orders_count',
            field=models.IntegerField(default=0, verbose_name='Размещено заказов'),
        ),
        migrations.AddField(
            model_name='user',
            name='rent_count',
            field=models.IntegerField(default=0, verbose_name='Взято в аренду'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe_type',
            field=models.ManyToManyField(to='technique.TechniqueType', verbose_name='Тип техники для оповещений'),
        ),
    ]
