# Generated by Django 3.0.8 on 2020-09-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0018_remove_techniquetype_orders_count'),
        ('user', '0006_auto_20200901_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribe_type',
            field=models.ManyToManyField(blank=True, to='technique.TechniqueType', verbose_name='Тип техники для оповещений'),
        ),
    ]
