# Generated by Django 3.0.8 on 2020-09-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=10000, verbose_name='Баланс'),
        ),
    ]
