# Generated by Django 3.0.8 on 2020-09-20 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200917_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(null=True, upload_to='payment/', verbose_name='Иконка')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название платежа')),
                ('method', models.CharField(blank=True, max_length=255, null=True, verbose_name='Метод платежа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
            ],
            options={
                'verbose_name': 'Вид платежа',
                'verbose_name_plural': 'Виды платежей',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='refferals',
            field=models.ManyToManyField(blank=True, related_name='_user_refferals_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус платежа')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Сумма платежа')),
                ('is_payed', models.BooleanField(default=False, verbose_name='Оплачен?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.PaymentType', verbose_name='Вид платежа')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
