# Generated by Django 3.0.8 on 2020-09-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_refferalmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentobj',
            name='pay_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа'),
        ),
    ]
