# Generated by Django 3.0.8 on 2020-10-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0021_techniqueunit_year'),
        ('user', '0016_auto_20200921_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='technique.TechniqueUnit', verbose_name='Избранное'),
        ),
    ]
