# Generated by Django 3.0.8 on 2020-10-11 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_refferalmoney_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refferal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned', models.IntegerField(blank=True, null=True, verbose_name='Начислено')),
                ('action', models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='Операция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начисления')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_user_money', to=settings.AUTH_USER_MODEL)),
                ('refferal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Рефферал')),
            ],
            options={
                'verbose_name': 'Начисление',
                'verbose_name_plural': 'Начисления',
            },
        ),
        migrations.RemoveField(
            model_name='refferals',
            name='master',
        ),
        migrations.RemoveField(
            model_name='refferals',
            name='slaves',
        ),
        migrations.DeleteModel(
            name='RefferalMoney',
        ),
        migrations.DeleteModel(
            name='Refferals',
        ),
    ]
