# Generated by Django 3.1.5 on 2021-02-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20201029_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_balance',
            field=models.IntegerField(default=1000, verbose_name='Партнерский баланс'),
        ),
    ]
