# Generated by Django 3.1.5 on 2021-03-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20210222_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='profile.svg', upload_to='user', verbose_name='Фото'),
        ),
    ]
