# Generated by Django 3.1.5 on 2021-05-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20210323_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notification_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID для сообщений'),
        ),
    ]
