# Generated by Django 4.0.6 on 2022-09-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20210531_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ref_code_entered',
            field=models.BooleanField(default=False, verbose_name='Код введен'),
        ),
    ]
