# Generated by Django 4.0.6 on 2022-09-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_user_is_ref_code_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='used_partner_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Партнерский код'),
        ),
    ]
