# Generated by Django 4.0.6 on 2022-10-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_user_used_partner_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free', models.BooleanField(default=False, verbose_name='Hазмещение платное')),
                ('vip_price', models.IntegerField(default=0, verbose_name='Надбавки за ВИП услуги')),
                ('up_price', models.IntegerField(default=0, verbose_name='Цена поднятия, если не указано, будет использована цена объявления')),
            ],
        ),
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'ordering': ('-created_at',)},
        ),
    ]
