# Generated by Django 4.0.6 on 2022-10-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_settings_alter_userfeedback_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='vip_time',
            field=models.IntegerField(default=30, verbose_name='Интервал ВИП услуг (поднять и закрепить) ХХ дней'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Размещение платное'),
        ),
    ]
