# Generated by Django 3.0.8 on 2020-09-01 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
        ('technique', '0016_auto_20200823_2035'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_apply', models.IntegerField(blank=True, null=True, verbose_name='Выбранная заявка')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_lower', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('rent_time', models.IntegerField(null=True, verbose_name='Время аренды')),
                ('rent_type', models.BooleanField(default=True, verbose_name='Тип аренды почасовая')),
                ('rentDate', models.DateField(blank=True, null=True)),
                ('rentStartDate', models.DateField(blank=True, null=True)),
                ('rentEndDate', models.DateField(blank=True, null=True)),
                ('rentStartTime', models.TimeField(blank=True, null=True)),
                ('rentEndTime', models.TimeField(blank=True, null=True)),
                ('comment', models.TextField(null=True, verbose_name='Описание')),
                ('is_moderated', models.BooleanField(default=True, verbose_name='Проверена?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Учавстует в выдаче?')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Выполнена?')),
                ('customer_feedback', models.BooleanField(default=False, verbose_name='Отзыв от заказчика')),
                ('worker_feedback', models.BooleanField(default=False, verbose_name='Отзыв от исполнителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.City', verbose_name='Местоположение')),
                ('filter', models.ManyToManyField(blank=True, related_name='order_filters', to='technique.TechniqueFilter', verbose_name='Фильтры')),
                ('filter_value', models.ManyToManyField(blank=True, related_name='order_filter_values', to='technique.TechniqueFilterValue', verbose_name='ФильтрыЗначения')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='technique.TechniqueType', verbose_name='Относится к типу')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
        ),
    ]
