# Generated by Django 3.0.8 on 2020-09-06 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0018_remove_techniquetype_orders_count'),
        ('order', '0002_ordertypesubscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='apply_units',
            field=models.ManyToManyField(to='technique.TechniqueUnit', verbose_name='Предложенная техника'),
        ),
        migrations.AddField(
            model_name='order',
            name='worker_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_unit', to='technique.TechniqueUnit', verbose_name='Исполнитель'),
        ),
        migrations.DeleteModel(
            name='OrderTypeSubscribe',
        ),
    ]
