# Generated by Django 3.0.8 on 2020-09-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200906_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
    ]
