# Generated by Django 3.0.8 on 2020-09-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_apply',
        ),
        migrations.AddField(
            model_name='order',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
