# Generated by Django 3.0.8 on 2020-09-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200906_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Координаты'),
        ),
    ]
