# Generated by Django 4.0.6 on 2022-11-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210320_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rentKm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='rent_type',
            field=models.BooleanField(blank=True, null=True, verbose_name='Тип аренды почасовая'),
        ),
    ]
